model:
  name: potential_model
  params:
    e_dress:
      1: -6.390549397295361
      6: -3.834329638377216
      7: -1.278109879459072
      8: -1.278109879459072
    e_loss_multiplier: 10
    e_scale: 1.0
    e_unit: 1.0
    f_loss_multiplier: 3000
    log_e_per_atom: true
    separate_errors: true
    use_e_per_atom: false
    no_force_comp: 10
    use_force: true
network:
  name: PiNet
  params:
    rc: 5.5
    depth: 4
    n_basis: 10
    basis_type: gaussian
    atom_types: [1, 6, 7, 8]
    ii_nodes:   [16, 16, 16]
    pp_nodes:   [16, 16, 16]
    pi_nodes:   [16]
    out_nodes:  [16]
optimizer:
  class_name: EKF
  config:
    learning_rate: 0.001
